# Circus tests Makefile
# Copyright (c) 2011 Ignasi Barrera
# This file is released under the MIT License, see LICENSE file.

all: test

test:
	cd .. && $(MAKE) $@

clean:
	cd .. && $(MAKE) clean-test
